load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# gRPC dependency
# See https://github.com/grpc/grpc/blob/master/src/cpp/README.md#bazel.

http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/de6defa6fff08de20e36f9168f5b277e292daf46.tar.gz",
    ],
    strip_prefix = "grpc-de6defa6fff08de20e36f9168f5b277e292daf46",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

# Extra deps are needed too. See https://github.com/grpc/grpc/issues/22436.
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
